### ISSUE TITLE
Paquetes faltantes en R

### ISSUE THREAD

**Issue by hvillalo** [Intercoonecta/Talleres_intermedios#5]
@emiliom, ya pasé mi tutorial al JupyterHub y me indicó que faltaban de instalar los paquetes satin (preferiría la versión de github: "hvillalo/satin") y smooth (de CRAN), aunque hace días los agregaste. Lo intenté yo (incluyendo "hvillalo/periods" porque añadí un último ejemplo) y mis dos paquetes (satin y periods) se instalaron sin problema, pero ignoro si los participantes deberán también hacerlo por su cuenta. En cambio 'smooth' falló por dos dependencias 'nloptr' y 'greybox'. Tendrás aun tiempo de ayudarme? Gracias de antemano y perdón por la premura...

**Comment by emiliom** [comment]
He pasado esto al issue ya existente sobre paquetes, https://github.com/Intercoonecta/tutoriales/issues/10#issuecomment-2418362085
